src/Controller/Security/ExceptionCompteDesactive.php
<?php


namespace App\Controller\Security;
use Symfony\Component\Security\Core\Exception\AccountStatusException;


class ExceptionCompteDesactive extends AccountStatusException
{
    /**
     * {@inheritdoc}
     */
    public function getMessageKey()
    {
        return 'Votre compte n\'est pas encore activé.';
    }
}

src/Controller/Security/SecurityController.php
<?php

namespace App\Controller\Security;

use App\Entity\User;
use App\Form\RegistrationType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;

class SecurityController extends AbstractController
{
    /**
     * @Route("/inscription", name="security_registration")
     */
    public function registration(Request $request, EntityManagerInterface  $em,
                                 UserPasswordEncoderInterface $encoder)
    {
        $user = new User();
        $form  = $this->createForm(RegistrationType::class, $user);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()) {
            $hash = $encoder->encodePassword($user,$user->getPassword());
            $user->setPassword($hash);

            $em->persist($user);
            $em->flush();
            return $this->redirectToRoute('security_login');
        }
        return $this->render('security/registration.html.twig',
            ['form' =>$form->createView()]);
    }

    /**
     * @Route("/connexion",name="security_login")
     */
    public function login(AuthenticationUtils  $authenticationUtils)
    {
        // get the login error if there is one
        $error = $authenticationUtils->getLastAuthenticationError();

        // last username entered by the user
        $lastUsername = $authenticationUtils->getLastUsername();

        return $this->render('security/login.html.twig',['lastUsername'=>$lastUsername,
            'error' => $error]);
    }

    /**
     * @Route("/deconnexion",name="security_logout")
     */
    public function logout()
    { }

    /**
     * Redirect users after login based on the granted ROLE
     * @Route("/login/redirect", name="login_redirect")
     */
    public function loginRedirectAction(Request $request)
    {
        if($this->isGranted('ROLE_ADMIN'))
        {
            return $this->redirectToRoute('sip_labo_index');
        }
        else if($this->isGranted('ROLE_LABO'))
        {
            return $this->redirectToRoute('labo');
        }
        else if($this->isGranted('ROLE_DELEGUE'))
        {
            return $this->redirectToRoute('delegue');
        }
        else if($this->isGranted('ROLE_MEDECIN'))
        {
            return $this->redirectToRoute('medecin');
        }
        else
        {
            return $this->redirectToRoute('security_login');
        }
    }




}

src/Controller/Security/VerificateurUser.php
<?php


namespace App\Controller\Security;
use App\Controller\Security\ExceptionCompteDesactive;
use App\Entity\User as AppUser;
use Symfony\Component\Security\Core\Exception\AccountExpiredException;
use Symfony\Component\Security\Core\User\UserCheckerInterface;
use Symfony\Component\Security\Core\User\UserInterface;


class VerificateurUser implements UserCheckerInterface
{
    public function checkPreAuth(UserInterface $user)
    {
        if (!$user instanceof AppUser) {
            return;
        }

        // L’utilisateur n’est pas activé par l’administrateur
        if (!$user->isActive()) {
            throw new ExceptionCompteDesactive();
        }
    }

    public function checkPostAuth(UserInterface $user)
    {

    }
}

templates/security/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello SecurityController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ '/home/dev-bassem/sip-lab/lb_sip/src/Controller/SecurityController.php'|file_link(0) }}">src/Controller/SecurityController.php</a></code></li>
        <li>Your template at <code><a href="{{ '/home/dev-bassem/sip-lab/lb_sip/templates/security/index.html.twig'|file_link(0) }}">templates/security/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

templates/security/login.html.twig
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width, initial-scale=1" name="viewport" />
    <meta name="description" content="Responsive Admin Template" />
    <meta name="author" content="RedstarHospital" />
    <title>Login</title>
    <!-- google font -->
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&amp;subset=all" rel="stylesheet"
          type="text/css" />
    <!-- icons -->
    <link href="{{ asset('assets/css/font-awesome.min.css')}}" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="{{ asset('assets/bundles/iconic/css/material-design-iconic-font.min.css')}}">
    <!-- bootstrap -->
    <link href="{{ asset('assets/bundles/bootstrap/css/bootstrap.min.css')}}" rel="stylesheet" type="text/css" />
    <!-- style -->
    <link rel="stylesheet" href="{{ asset('assets/css/extra_pages.css')}}">
    <!-- favicon -->
    <link rel="shortcut icon" href="{{ asset('assets/img/favicon.ico')}}" />
</head>

<body>
<div class="limiter">
    <div class="container-login100 page-background">
        <div class="wrap-login100">
            {% if error %}
                <div>{{ error.messageKey|trans(error.messageData, 'security') }}</div>
            {% endif %}
            <form action="{{ path('security_login') }}" method="post" class="login100-form validate-form">
                <input type="hidden" name="_csrf_token"
                       value="{{ csrf_token('authenticate') }}"
                >
                <span class="login100-form-logo">
						<img alt="" src="{{ asset('assets/img/hospital.png')}}">
					</span>
                <span class="login100-form-title p-b-34 p-t-27">
						Log in
					</span>
                <div class="wrap-input100 validate-input" data-validate="Enter username">
                    <input class="input100" type="text" required name="_username" value ="{{lastUsername}}" placeholder="Username">
                    <span class="focus-input100" data-placeholder="&#xf207;"></span>
                </div>
                <div class="wrap-input100 validate-input" data-validate="Enter password">
                    <input class="input100" type="password" required name="_password" placeholder="Password">
                    <span class="focus-input100" data-placeholder="&#xf191;"></span>
                </div>
                <div class="contact100-form-checkbox">
                    <input class="input-checkbox100" id="ckb1" type="checkbox" name="remember-me">
                    <label class="label-checkbox100" for="ckb1">
                        Remember me
                    </label>
                </div>
                <div class="container-login100-form-btn">
                    <button type="submit" class="login100-form-btn">
                        Login
                    </button>
                </div>
                <div class="text-center p-t-30">
                    <a class="txt1" href="forgot_password.html">
                        Forgot Password?
                    </a>
                </div>
            </form>
        </div>
    </div>
</div>
<!-- start js include path -->
<script src="{{ asset('assets/bundles/jquery/jquery.min.js')}}"></script>
<!-- bootstrap -->
<script src="{{ asset('assets/bundles/bootstrap/js/bootstrap.min.js')}}"></script>
<script src=".{{ asset('assets/data/login-data.js')}}"></script>
<!-- end js include path -->
</body>


<!-- Mirrored from radixtouch.in/templates/admin/redstar/source/light/login.html by HTTrack Website Copier/3.x [XR&CO'2014], Fri, 10 Apr 2020 23:42:31 GMT -->
</html>



templates/security/registration.html.twig
{% extends 'base.html.twig' %}

{% block title %}Inscription{% endblock %}

{% block body %}
    <h1>Inscription sur le site</h1>
    {{ form_start(form) }}
    {{ form_row(form.nom, { 'attr': {  'placeholder': 'nom' } }  ) }}
    {{ form_row(form.prenom, { 'attr': {  'placeholder': 'prenom' } }  ) }}
    {{ form_row(form.adresse, { 'attr': {  'placeholder': 'adresse' } }  ) }}
    {{ form_row(form.tel, { 'attr': {  'placeholder': 'tel' } }  ) }}


    {{ form_row(form.email, { 'attr': {  'placeholder': 'Adresse email...' } }  ) }}
    {{ form_row(form.username, { 'label':'Nom d\'utilisateur', 'attr': {'placeholder':'Nom d\'utilisateur...' } }) }}
    {{ form_row(form.password, { 'label':'Mot de passe', 'attr': {'placeholder':'Mot de passe...' } }) }}
    {{ form_row(form.confirm_password, { 'label':'Répétez votre mot de passe',
        'attr':{'placeholder':'Répétez votre mot de passe...' } }) }}
    <button type="submit" class="btn btn-success">Inscription</button>
    {{ form_end(form) }}
{% endblock %}